### ISSUE TITLE
How to run __main__.py

### ISSUE THREAD

**Issue by SinisaDakovic** [edde746/tiktok-askreddit#12]
Command `python3 __main__.py` returns:
Traceback (most recent call last):
  File "/home/kali/Desktop/bott/tiktok-askreddit/__main__.py", line 3, in <module>
    from scraper import scrape
  File "/home/kali/Desktop/bott/tiktok-askreddit/scraper.py", line 1, in <module>
    import time,utils,string
  File "/home/kali/Desktop/bott/tiktok-askreddit/utils.py", line 5, in <module>
    config = yaml.safe_load(open('config.yaml').read())
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 1, column 1:
    debug: true
    ^
expected <block end>, but found '<scalar>'
  in "<unicode string>", line 3, column 208:
     ... RESVQifX0=; over18=1; g_state={"i_l":0}; pc=5s; recent_srs=t5_6e ...

**Comment by edde746** [comment]
Your config yaml has a syntax error.
