### ISSUE TITLE
__main__.py not working properly

### ISSUE THREAD

**Issue by pietjestacks** [edde746/tiktok-askreddit#13]
Command python3 __main__.py returns:
Traceback (most recent call last):
  File "/Users/teunkrol/Documents/GitHub/tiktok-askreddit/__main__.py", line 1, in <module>
    import asyncio,tts,os,video,requests
  File "/Users/teunkrol/Documents/GitHub/tiktok-askreddit/tts.py", line 2, in <module>
    import edge_tts
ModuleNotFoundError: No module named 'edge_tts'

Do you know how I could fix this?

**Comment by edde746** [comment]
Install the requirements
