### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Multiversed** [edde746/tiktok-askreddit#18]
Screenshotting post...
Traceback (most recent call last):
  File "C:\Users\lenovo\Downloads\tiktok-askreddit-main\tiktok-askreddit-main\__main__.py", line 61, in <module>
    asyncio.run(main())
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\lenovo\Downloads\tiktok-askreddit-main\tiktok-askreddit-main\__main__.py", line 56, in main
    raise e
  File "C:\Users\lenovo\Downloads\tiktok-askreddit-main\tiktok-askreddit-main\__main__.py", line 33, in main
    data = scrape(url)
  File "C:\Users\lenovo\Downloads\tiktok-askreddit-main\tiktok-askreddit-main\scraper.py", line 78, in scrape
    raise e
  File "C:\Users\lenovo\Downloads\tiktok-askreddit-main\tiktok-askreddit-main\scraper.py", line 21, in scrape
    post_text = post.find_element_by_css_selector('h1').text
AttributeError: 'WebElement' object has no attribute 'find_element_by_css_selector'

**Comment by kingpinofsteel** [comment]
Did you manage to fix this, and how? It's happening to me.
