### ISSUE TITLE
Im getting a error

### ISSUE THREAD

**Issue by turtlesiscool** [edde746/tiktok-askreddit#6]
It says failed to upload, it writes the tags and comment and then boom it crashes

**Comment by edde746** [comment]
Provide more context, do some logging, enable debugging in the config to get it to print out full error messages.

**Comment by turtlesiscool** [comment]
okay will do it in a few h when i'm back from work

**Comment by turtlesiscool** [comment]
this is the first error im getting


Op za 14 mei 2022 om 12:35 schreef edde746 ***@***.***>:

**Comment by Catchii** [comment]
im also getting an error

```
🎥 Rendering video...
Traceback (most recent call last):
  File "C:\Users\catch\Desktop\Python Projects\Neuer Ordner\tiktok-askreddit-main\__main__.py", line 61, in <module>
    asyncio.run(main())
  File "C:\Users\catch\AppData\Local\Programs\Python\Python37\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\catch\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "C:\Users\catch\Desktop\Python Projects\Neuer Ordner\tiktok-askreddit-main\__main__.py", line 56, in main
    raise e
  File "C:\Users\catch\Desktop\Python Projects\Neuer Ordner\tiktok-askreddit-main\__main__.py", line 47, in main
    if video.render(name):
  File "C:\Users\catch\Desktop\Python Projects\Neuer Ordner\tiktok-askreddit-main\video.py", line 34, in render
    background_clip = "backgrounds/" + random.choice(os.listdir("backgrounds"))
  File "C:\Users\catch\AppData\Local\Programs\Python\Python37\lib\random.py", line 261, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[Verarbeitung des Prozesses mit Code 1 (0x00000001) beendet]
```

**Comment by edde746** [comment]
@turtlesiscool You didn't send anything...
@Catchii You haven't put any background clips in the `backgrounds` directory.

**Comment by Catchii** [comment]
yeah i just noticed xd also there is an bug with long titles

the description is weird on long reddit posts

instead of 

how do you feel right now? hows your life? #fyp #reditt

it turns into

how_do_you_feel_right_now?_hows_your_life?

with no hashtags

**Comment by heensuk** [comment]
Hello dear @edde746

There's a problem with comments, if there aren't comments in the post, it throws an error, and if there's a comment with no letter it shows an error either.
It'd be cool if we can choose a minimum number of comments and pass posts with 0 comments.

(No comments)
![image](https://user-images.githubusercontent.com/94083869/168485469-8218c91a-e62a-416b-8156-575ff4a7ef47.png)

(No words or letter in comment)
![image](https://user-images.githubusercontent.com/94083869/168485341-7a01ce4b-67b5-4b80-b41f-681df8bb9fa4.png)

**Comment by turtlesiscool** [comment]
This is the error :
![Screenshot_37](https://user-images.githubusercontent.com/75637639/168485778-97eedc68-e823-4c7d-96d9-ea66574eaadf.png)
 
and when the title is long, it will add underscores and it wont add hashtags

and it will be nice if there's a option that it wont scrape comments, so you can bassicly do long stories if thats possible

**Comment by heensuk** [comment]
> This is the error : ![Screenshot_37](https://user-images.githubusercontent.com/75637639/168485778-97eedc68-e823-4c7d-96d9-ea66574eaadf.png)
> 
> and when the title is long, it will add underscores and it wont add hashtags
> 
> and it will be nice if there's a option that it wont scrape comments, so you can bassicly do long stories if thats possible

Does it  even take a screenshot of something?

**Comment by turtlesiscool** [comment]
nope
