### ISSUE TITLE
Trying To Screen shot i.redd.it

### ISSUE THREAD

**Issue by Catchii** [edde746/tiktok-askreddit#7]
Trying To Screen shot i.redd.it

After About 30S I get an error

```
⏱ Processing post: i.redd.it
📸 Screenshotting post...

DevTools listening on ws://127.0.0.1:59418/devtools/browser/138cc65b-36e8-46e7-b700-018684ac818f
Traceback (most recent call last):
  File "C:\Users\catch\Desktop\Python Projects\Neuer Ordner\tiktok-askreddit-main\__main__.py", line 61, in <module>
    asyncio.run(main())
  File "C:\Users\catch\AppData\Local\Programs\Python\Python37\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\catch\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "C:\Users\catch\Desktop\Python Projects\Neuer Ordner\tiktok-askreddit-main\__main__.py", line 56, in main
    raise e
  File "C:\Users\catch\Desktop\Python Projects\Neuer Ordner\tiktok-askreddit-main\__main__.py", line 33, in main
    data = scrape(url)
  File "C:\Users\catch\Desktop\Python Projects\Neuer Ordner\tiktok-askreddit-main\scraper.py", line 78, in scrape
    raise e
  File "C:\Users\catch\Desktop\Python Projects\Neuer Ordner\tiktok-askreddit-main\scraper.py", line 20, in scrape
    post = WebDriverWait(bot, 20).until(EC.presence_of_element_located((By.CSS_SELECTOR, '.Post')))
  File "C:\Users\catch\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x00D9B8F3+2406643]
        Ordinal0 [0x00D2AF31+1945393]
        Ordinal0 [0x00C1C748+837448]
        Ordinal0 [0x00C492E0+1020640]
        Ordinal0 [0x00C4957B+1021307]
        Ordinal0 [0x00C76372+1205106]
        Ordinal0 [0x00C642C4+1131204]
        Ordinal0 [0x00C74682+1197698]
        Ordinal0 [0x00C64096+1130646]
        Ordinal0 [0x00C3E636+976438]
        Ordinal0 [0x00C3F546+980294]
        GetHandleVerifier [0x01009612+2498066]
        GetHandleVerifier [0x00FFC920+2445600]
        GetHandleVerifier [0x00E34F2A+579370]
        GetHandleVerifier [0x00E33D36+574774]
        Ordinal0 [0x00D31C0B+1973259]
        Ordinal0 [0x00D36688+1992328]
        Ordinal0 [0x00D36775+1992565]
        Ordinal0 [0x00D3F8D1+2029777]
        BaseThreadInitThunk [0x765E6739+25]
        RtlGetFullPathName_UEx [0x77D58FEF+1215]
        RtlGetFullPathName_UEx [0x77D58FBD+1165]
```

**Comment by Catchii** [comment]
@edde746
