### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by crafti12** [edde746/tiktok-askreddit#8]
⏱ Processing post: germans_of_reddit_what_are_some_things_you_have
📸 Screenshotting post...
Traceback (most recent call last):
  File "D:\Pobrane (na serio)\tiktok-askreddit\__main__.py", line 61, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\Pobrane (na serio)\tiktok-askreddit\__main__.py", line 56, in main
    raise e
  File "D:\Pobrane (na serio)\tiktok-askreddit\__main__.py", line 33, in main
    data = scrape(url)
  File "D:\Pobrane (na serio)\tiktok-askreddit\scraper.py", line 78, in scrape
    raise e
  File "D:\Pobrane (na serio)\tiktok-askreddit\scraper.py", line 16, in scrape
    bot.add_cookie({'name':cookie_data[0],'value':cookie_data[1],'domain':'reddit.com'})
IndexError: list index out of range

**Comment by crafti12** [comment]
@edde746

**Comment by Kasperny** [comment]
[PL]
Po folderze widzę, że jesteś polakiem, a ja miałem ten sam błąd więc udzielę swojej rady. Przy kopiowaniu "sent cookies", zamiast np. set-cookie skopiuj header cookie bądź cookies (zarówno na tiktoku jak i reddicie).
[ENG] 
I had a similar issue so I'll give you my advice. When copying "sent cookies", instead of for example: set-cookie copy the cookie or cookies header (For tiktok and reddit).
